// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wegentSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wegent',
    },
  ],
  weworkSidebar: [
    {
      type: 'autogenerated',
      dirName: 'wework',
    },
  ],
};

export default sidebars;
