# Sync Documentation to Docs Repository
#
# This workflow should be placed in the main Wegent repository (wecode-ai/Wegent)
# at .github/workflows/sync-docs.yml
#
# It automatically syncs documentation changes to the wegent-docs repository
# when changes are made to the docs/ directory.
#
# Requirements:
# - A Personal Access Token (PAT) with repo scope stored as DOCS_REPO_TOKEN secret
# - The PAT must have write access to wecode-ai/wegent-docs repository

name: Sync Documentation to Docs Repository

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  trigger-docs-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs repository sync
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          repository: wecode-ai/wegent-docs
          event-type: docs-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Log sync trigger
        run: |
          echo "Documentation sync triggered for commit ${{ github.sha }}"
          echo "Changes in docs/ directory detected and sync dispatched to wegent-docs repository"
